#include "game.h"
#include "player.h"
#include <stdbool.h>

int player_standing[ROWS][COLS] = {
    {BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, GREEN, RED, GREEN, GREEN, GREEN, GREEN, RED, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, GREEN, RED, GREEN, GREEN, GREEN, GREEN, RED, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, GREEN, RED, GREEN, GREEN, GREEN, GREEN, RED, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, GREEN, RED, GREEN, GREEN, GREEN, GREEN, RED, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK},
    {GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK},
    {YELLOW, YELLOW, GREEN, GREEN, RED, YELLOW, RED, RED, RED, RED, YELLOW, RED, GREEN, GREEN, YELLOW, YELLOW, BLACK, BLACK, BLACK},
    {YELLOW, YELLOW, YELLOW, GREEN, RED, RED, RED, RED, RED, RED, RED, RED, GREEN, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK},
    {YELLOW, YELLOW, YELLOW, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK},
    {BLACK, YELLOW, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, RED, RED, RED,  RED, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, RED, RED, RED,  RED, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, RED, RED, RED,  RED, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK}
};
int player_walking1[ROWS][COLS]={
    {BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, GREEN, GREEN, RED, BLACK, BLACK, BLACK, YELLOW, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, RED, BLACK, YELLOW, YELLOW, YELLOW},
    {BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, RED, GREEN, YELLOW, YELLOW, YELLOW},
    {BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, RED, YELLOW, YELLOW, YELLOW},
    {BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, RED, GREEN, YELLOW, GREEN},
    {BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, RED, GREEN, GREEN, BLACK},
    {GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, RED, RED, RED, YELLOW, RED, GREEN, YELLOW, GREEN, BLACK, BLACK},
    {GREEN, GREEN, GREEN, GREEN, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK},
    {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK},
    {YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, GREEN},
    {YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, GREEN, GREEN},
    {BLACK, YELLOW, YELLOW, YELLOW, RED, RED, RED, RED, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN},
    {BLACK, BLACK, BLACK, RED, GREEN, RED, RED, RED, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN},
    {BLACK, BLACK, GREEN, RED, RED, GREEN, RED, RED, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN},
    {GREEN, GREEN, GREEN, RED, RED, RED, GREEN, GREEN, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN},
    {GREEN, GREEN, GREEN, GREEN, RED, RED, RED, RED, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN},
    {GREEN, GREEN, GREEN, GREEN, GREEN, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK}
};
int player_walking2[ROWS][COLS]={
    {BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, RED, RED, RED, YELLOW, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, GREEN, RED, GREEN, GREEN, GREEN, RED, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, GREEN, RED, GREEN, GREEN, GREEN, GREEN, RED, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, GREEN, RED, GREEN, GREEN, GREEN, GREEN, GREEN, RED, RED, YELLOW, YELLOW, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW},
    {BLACK, BLACK, BLACK, GREEN, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, GREEN, GREEN, GREEN, RED, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED, GREEN, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, GREEN, RED, RED, RED, RED, RED, RED, RED, GREEN, RED, RED, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, GREEN, RED, RED, RED, RED, RED, GREEN, GREEN, RED, RED, RED, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, GREEN, RED, RED, RED, RED, GREEN, RED, RED, RED, RED, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, GREEN, RED, RED, RED, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK},
    {BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK},
    {BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK}

};
int player_jumping[ROWS][COLS] = {
    {BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, YELLOW, BLACK, BLACK, BLACK}, 
    {BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, YELLOW, YELLOW, GREEN, GREEN, YELLOW, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, GREEN, GREEN, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, GREEN, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW, YELLOW, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, YELLOW, GREEN, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, BLACK, BLACK, BLACK},  
    {BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, GREEN, GREEN, RED, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, RED, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN ,RED, GREEN, GREEN, RED, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, RED, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, RED, RED, RED, RED, GREEN, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, RED, RED, RED, RED, YELLOW, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, YELLOW, BLACK, YELLOW, YELLOW, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, BLACK, GREEN, BLACK, BLACK, BLACK},
    {BLACK, BLACK, YELLOW, YELLOW, RED, RED, RED, RED, RED, RED, RED, RED, RED, RED, BLACK, GREEN, GREEN, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, RED, RED, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, BLACK, GREEN, RED, RED, RED, RED, RED, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, GREEN, GREEN, RED, RED, RED, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, RED, RED, GREEN, GREEN, RED, RED, RED, RED, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, RED, RED, RED, RED, BLACK, BLACK, RED, RED, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, GREEN, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK, BLACK}
};
int player_dead[ROWS][COLS] = {
    {BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, YELLOW, BLACK, RED, RED, RED, RED, RED, RED, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK},
    {YELLOW, YELLOW, YELLOW, GREEN, YELLOW, GREEN, YELLOW, YELLOW, GREEN, YELLOW, GREEN, YELLOW, YELLOW, YELLOW},
    {YELLOW, YELLOW, GREEN, GREEN, YELLOW, GREEN, YELLOW, YELLOW, GREEN, YELLOW, GREEN, GREEN, YELLOW, YELLOW},
    {YELLOW, YELLOW, GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, YELLOW, YELLOW},
    {BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, GREEN, GREEN, GREEN, GREEN, YELLOW, GREEN, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, BLACK, BLACK, BLACK},
    {BLACK, BLACK, RED, RED, RED, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, RED, BLACK, BLACK},
    {BLACK, GREEN, GREEN, RED, RED, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, RED, RED, GREEN, GREEN, GREEN, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, YELLOW, RED, RED, YELLOW, RED, GREEN, GREEN, GREEN, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, RED, RED, RED, RED, RED, GREEN, GREEN, GREEN, BLACK},
    {BLACK, BLACK, GREEN, GREEN, RED, RED, RED, RED, RED, RED, GREEN, GREEN, BLACK, BLACK}
};


bool frameToggle = false; 
bool isFacingLeft = false; // Default menghadap ke kanan
int (*currentCharacter)[COLS] = player_standing; // Default adalah standing

void drawCharacter(int player[ROWS][COLS], int x, int y, bool hasStarPower) {
    int characterHeight = 50; // Total tinggi karakter
    int adjustedY = y - characterHeight; // Sesuaikan Y agar kaki menjadi referensi

    for (int i = 0; i < ROWS; i++) {
        for (int j = 0; j < COLS; j++) {
            if (player[i][j] != BLACK) { // Hanya menggambar piksel yang bukan hitam
                int color = player[i][j]; // Warna asli dari array

                // Ubah warna berdasarkan kondisi power-up
                if (hasStarPower) {
                    if (color == RED) color = GREEN1;
                    else if (color == GREEN) color = YELLOW1;
                    else if (color == YELLOW) color = WHITE;
                }

                setfillstyle(SOLID_FILL, color); // Atur warna sesuai kondisi
                bar(
                    x + j * PLAYER_SIZE,                // Koordinat kiri atas pixel
                    adjustedY + i * PLAYER_SIZE,        // Koordinat atas pixel
                    x + (j + 1) * PLAYER_SIZE,          // Koordinat kanan bawah pixel
                    adjustedY + (i + 1) * PLAYER_SIZE   // Koordinat bawah pixel
                );
            }
        }
    }

    // Tambahkan efek aura jika power-up aktif
    if (hasStarPower) {
        setcolor(GREEN1); // Warna aura (contoh warna power-up)
        setfillstyle(SOLID_FILL, GREEN1);
        fillellipse(
            x + COLS / 2 * PLAYER_SIZE,                // Pusat aura (X)
            adjustedY + ROWS / 2 * PLAYER_SIZE,        // Pusat aura (Y)
            COLS * PLAYER_SIZE / 2 + 5,               // Lebar aura
            ROWS * PLAYER_SIZE / 2 + 5                // Tinggi aura
        );
    }
}


int player_standing_mirrored[ROWS][COLS];
int player_walking1_mirrored[ROWS][COLS];
int player_walking2_mirrored[ROWS][COLS];
int player_jumping_mirrored[ROWS][COLS];

void initializeMirrorSprites() {
    mirrorPlayer(player_standing, player_standing_mirrored);
    mirrorPlayer(player_walking1, player_walking1_mirrored);
    mirrorPlayer(player_walking2, player_walking2_mirrored);
    mirrorPlayer(player_jumping, player_jumping_mirrored);
}

// Fungsi untuk mencerminkan (mirroring) array
void mirrorPlayer(int currentCharacter[ROWS][COLS], int mirrored[ROWS][COLS]) {
    for (int i = 0; i < ROWS; i++) {
        for (int j = 0; j < COLS; j++) {
            mirrored[i][j] = currentCharacter[i][COLS - 1 - j]; // Membalikkan arah kolom
        }
    }
}


// Fungsi untuk menangani input dari pemain
void handleInput() {
    if (!isAlive) { 
        // Ganti ke animasi mati jika karakter tidak hidup
        currentCharacter = player_dead;
        return;
    }

    if (kbhit()) {
        char key = getch();

        // Pergerakan ke kiri
        if (key == 'a' && playerX > 0) { 
            isFacingLeft = true; // Tandai karakter menghadap ke kiri
            if (playerX <= SCREEN_WIDTH / 2 && cameraX > 0) {
                cameraOffset -= SCROLL_SPEED;
                if (cameraOffset <= -SCREEN_WIDTH / MAP_WIDTH * 2) {
                    cameraOffset = 0;
                    cameraX -= 2; // Geser kamera jika mencapai batas
                }
            } else {
                playerX -= MOVE_SPEED; // Gerakkan karakter ke kiri
            }

            // Toggle animasi berjalan mirrored
            currentCharacter = (frameToggle) ? player_walking1_mirrored : player_walking2_mirrored;
            frameToggle = !frameToggle; // Ganti frame animasi
        }
        // Pergerakan ke kanan
        else if (key == 'd' && playerX < SCREEN_WIDTH) { 
            isFacingLeft = false; // Tandai karakter menghadap ke kanan
            if (playerX >= SCREEN_WIDTH / 2 && cameraX < TOTAL_MAP_WIDTH - MAP_WIDTH) {
                cameraOffset += SCROLL_SPEED;
                if (cameraOffset >= SCREEN_WIDTH / MAP_WIDTH * 2) {
                    cameraOffset = 0;
                    cameraX += 2; // Geser kamera jika mencapai batas
                }
            } else {
                playerX += MOVE_SPEED; // Gerakkan karakter ke kanan
            }

            // Toggle animasi berjalan normal
            currentCharacter = (frameToggle) ? player_walking1 : player_walking2;
            frameToggle = !frameToggle; // Ganti frame animasi
        }
        // Karakter melompat
        else if (key == 'w' && !isJumping) { 
            velocityY = JUMP_STRENGTH; // Set kecepatan awal melompat
            isJumping = 1; // Tandai status melompat
            currentCharacter = player_jumping; // Gunakan animasi melompat
        }
    }

    // Gunakan animasi berdiri jika tidak ada input dan karakter tidak melompat
    if (!kbhit() && velocityY == 0 && !isJumping) {
        currentCharacter = isFacingLeft ? player_standing_mirrored : player_standing;
    }
}

