#include "player.h"
#include "player_dead.h"

// Representasi Mario dalam array 14x14
int player_dead[ROWS][COLS] = {
    {BLACK, BLACK, BLACK, BLACK, BLACK, RED, RED, RED, RED, BLACK, BLACK, BLACK, BLACK, BLACK},
    {BLACK, BLACK, YELLOW, BLACK, RED, RED, RED, RED, RED, RED, BLACK, YELLOW, BLACK, BLACK, BLACK, BLACK, BLACK},
    {YELLOW, YELLOW, YELLOW, GREEN, YELLOW, GREEN, YELLOW, YELLOW, GREEN, YELLOW, GREEN, YELLOW, YELLOW, YELLOW},
    {YELLOW, YELLOW, GREEN, GREEN, YELLOW, GREEN, YELLOW, YELLOW, GREEN, YELLOW, GREEN, GREEN, YELLOW, YELLOW},
    {YELLOW, YELLOW, GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, YELLOW, YELLOW},
    {BLACK, BLACK, GREEN, GREEN, GREEN, GREEN, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, GREEN, GREEN, GREEN, GREEN, YELLOW, GREEN, BLACK, BLACK, BLACK},
    {BLACK, BLACK, BLACK, GREEN, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, BLACK, BLACK, BLACK},
    {BLACK, BLACK, RED, RED, RED, YELLOW, YELLOW, YELLOW, YELLOW, RED, RED, RED, BLACK, BLACK},
    {BLACK, GREEN, GREEN, RED, RED, GREEN, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, RED, GREEN, GREEN, RED, RED, GREEN, GREEN, GREEN, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, YELLOW, RED, RED, YELLOW, RED, GREEN, GREEN, GREEN, BLACK},
    {BLACK, GREEN, GREEN, GREEN, RED, RED, RED, RED, RED, RED, GREEN, GREEN, GREEN, BLACK},
    {BLACK, BLACK, GREEN, GREEN, RED, RED, RED, RED, RED, RED, GREEN, GREEN, BLACK, BLACK}
};